### ISSUE TITLE
improve gh workflow

### ISSUE THREAD

**Issue by Cattn** [bunkerweb/bunker#11]

**Comment by Cattn** [comment]
Done on @Nailington fork, waiting to be merged to archive creation branch

**Comment by Nailington** [comment]
PR https://github.com/bunkerweb/bunker/pull/13 has been closed. This contained the new workflow file to enable releases and a pushed commit to a branch dedicated to the built dist.

@Cattn please actually reference the repo, PR, issue, or commit directly with a link when they are available to be referenced?

**Comment by Cattn** [comment]
Meh
